### ISSUE TITLE
dashboard: have a side-panel to toggle data series visibility

### ISSUE THREAD

**Issue by mozkeeler** [mozkeeler/sunlight#51]
Somehow we did this with the pinning telemetry dashboard (i.e. you could click on a series to toggle its visibility).

**Comment by monicachew** [comment]
Yeah, in the pinning dashboard i think it just refetches all the telemetry data for a different release channel and redraws everything. I think we can build all the data in db2json then do some sort of AJAXy fetch on demand when someone wants to switch views.
